### ISSUE TITLE
Rajouter options dans Panel

### ISSUE THREAD

**Issue by Jackigeo** [IlonaBaran/oracles#33]
* Selectionner scenarios

**Comment by Erzalt** [comment]
Options trouvées:
-  sélectionner les scénario (possibilité de plusieurs à la fois) https://primevue.org/multiselect/#filter
- sélectionner les graphiques possibles en fonction du nombre de scénarios sélectionnés (prends en compte les variantes de graphiques) https://primevue.org/cascadeselect/
- lancer la requête
